# Generated by Django 2.0.2 on 2018-02-24 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer',
            fields=[
                ('answer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.IntegerField()),
                ('is_skipped', models.PositiveSmallIntegerField()),
                ('time_taken', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('ques_id', models.AutoField(primary_key=True, serialize=False)),
                ('statement', models.CharField(max_length=500)),
                ('op1', models.CharField(max_length=300)),
                ('op2', models.CharField(max_length=300)),
                ('op3', models.CharField(max_length=300)),
                ('op4', models.CharField(max_length=300)),
                ('ans', models.CharField(max_length=300)),
                ('correct', models.IntegerField()),
                ('incorrect', models.IntegerField()),
                ('TCI', models.FloatField()),
                ('time', models.FloatField()),
                ('clusters', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('stars', models.IntegerField()),
                ('badges', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('clusters', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subUser', to='play.subject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ques_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ansQuesID', to='play.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ansSub', to='play.subject'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ansUserID', to='play.user'),
        ),
    ]
